steps:
  - label: "Run unit tests"
    key: run_unit_tests
    plugins:
      - docker#v3.11.0:
          image: node:12
    commands:
      - "yarn"
      - "yarn build"
    artifact_paths:
      - ./coverage/lcov.info

  ## sonarqube
  # set the necessary sonarqube properties
  - label: ":sonarqube: Complete Sonarqube Properties"
    key: sonarqube_upload
    depends_on:
      - run_unit_tests
    command: .buildkite/sonarqube_upload.sh
    artifact_paths:
      - ./sonar-project.properties
    if: build.env("RELEASE_VERSION") == null

  # download the test results/sonar-project.properties with the artifacts plugin.
  # run sonar-scanner docker container for uploading analysis to sonarqube
  - label: ":sonarqube: Sonarqube"
    key: sonarqube
    if: build.env("RELEASE_VERSION") == null
    depends_on:
      - sonarqube_upload
    plugins:
      - artifacts#v1.3.0:
          download:
            - "sonar-project.properties"
            - "coverage/lcov.info"
      - docker#v3.13.0:
          image: "sonarsource/sonar-scanner-cli"
          environment:
            - "SONAR_HOST_URL=https://sonarqube.corp.twilio.com"
            - "SONAR_LOGIN=ef2e8f434cd8f7a2ed4a503ec3d92f93c06bf104"
